### ISSUE TITLE
How to show ui.icon component in table

### ISSUE THREAD

**Issue by zhuoqun-chen** [CrystalWindSnake/nicegui-tabulator#15]
Hi developer,

Thank you for making this amazing package!

I’d like to ask whether there is a way to show icons inside the table and make it rendered automatically instead of
the default demo example that only allows value changes in the table?

**Comment by CrystalWindSnake** [comment]
@zhuoqun-chen I'm sorry, I missed your message. Icons can be displayed in cells through the 'add_cell_slot' method, but currently, their data must be provided.

```python
from nicegui_tabulator import tabulator, CellSlotProps
from nicegui import ui


tabledata = [
    {"id": 1, "icon": "home", "age": "12"},
    {"id": 2, "icon": "star", "age": "24"},
]


table_config = {
    "data": tabledata,
    "columns": [
        {"title": "icon", "field": "icon"},
        {"title": "age", "field": "age"},
    ],
}


@ui.page("/")
def page():
    table = tabulator(table_config).classes("w-full h-fit max-h-[100vh]")

    @table.add_cell_slot("icon")
    def _(props: CellSlotProps):
        ui.label(props.value)
        ui.icon(props.value)

```

**Comment by zhuoqun-chen** [comment]
Thank you @CrystalWindSnake for the code snippet!
