### ISSUE TITLE
update_column_definition doesn't do anything

### ISSUE THREAD

**Issue by jameshall9** [CrystalWindSnake/nicegui-tabulator#31]
When I try use the method `update_column_defintion()` nothing happens. Here is an example similar to the example in Readme and it doesn't have any effect. I actually want to revert the formatting in this column to be plaintext but as that wasn't working I thought I would try a more simple changing if the title. 

`table_config ={'columnDefaults':{
                                'headerSort':False,
                                'formatter': 'money',
                                'formatterParams': {
                                    'decimal': '.',
                                    'thousand': ',',
                                    'negativeSign': True ,
                                    'precision': False,
                                    }
                                }
                            }
                            table= tabulator.from_pandas(df,options=table_config).style('font-size: 75%')
                            table.update_column_definition('index',{'title':"Inst"})`

I'm using version 0.2.0

**Comment by jameshall9** [comment]
@CrystalWindSnake thanks for  replying.  You have given me a clue as to where the problem lies. I build the table in an async function which awaits data from a database. I have mimicked this with `asyncio.sleep()` and I get the problem I am talking about. here is a full example.

```
import asyncio
from nicegui_tabulator import tabulator
from nicegui import ui
import pandas as pd

@ui.page("/")
def page():
    df = pd.DataFrame(
        {
            "index": [1, 2, 3],
            "name": ["Alice", "Bob", "Charlie"],
            "age": [25, 30, 35],
            "salary": [50000, 60000, 70000],
        }
    )

    async def build_table():

        await asyncio.sleep(1)
        table_config = {
            "columnDefaults": {
                "headerSort": False,
                "formatter": "money",
                "formatterParams": {
                    "decimal": ".",
                    "thousand": ",",
                    "negativeSign": True,
                    "precision": False,
                },
            }
        }
        table = tabulator.from_pandas(df, options=table_config).style("font-size: 75%")
        table.update_column_definition("index", {"title": "Inst"})

    ui.button('build table',on_click=build_table)

ui.run()
```

**Comment by CrystalWindSnake** [comment]
@jameshall9 Oh, the problem is likely that component methods cannot be called immediately after creating the component. I'll try to fix it later.
